// <auto-generated />
namespace E_Commerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ch32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ch32));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041318303_ch32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
